on:
  push:


permissions: 
  contents: write

jobs:
   run-script:
     name: Fetch data
     runs-on: ubuntu-latest
     steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Set git identity
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'

        - name: install requests
          run: |
            pip install requests

        - name: Run python program
          shell: bash
          run: |
            ./getfiles.sh
          
        - name: File Listing
          run: |
            ls -R

        - name: Git Status
          run: |
            git status
            
        - name: Add to git
          run: |
            git add .
            
        - name: Commit to git
          run: |
            git commit -m "Update data" || echo "No changes to commit"
            
        - name: Git Status
          run: |
            git status
            
        - name: Git Push
          run: |
            git status
            git push
            
        - name: Git Status
          run: |
            git status
