name: add new planes

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions: 
  contents: write

jobs:
   run-script:
     name: Fetch data
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
     
     steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Set git identity
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'

        - name: install requests
          run: |
            python -m pip install --upgrade pip
            pip install requests
    
        - name: Run weather logging script
          run: python adsbgetphotosdb.py

        - name: Commit and push if changed
          run: |
            ls -R
            git status
            git add .
            git commit -m "Update data" || echo "No changes to commit"
            git status
            git status
            git push
            git status

